#!/bin/bash

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    
find . -name "Version.java" | while read versionfile; do

    echo "Replacing tags in ${versionfile}"
    
    sed -i "s@<BUILD_ID>@${BUILD_ID}@g"         ${versionfile}
    sed -i "s@<TIMESTAMP>@${TIMESTAMP}@g"       ${versionfile}
    sed -i "s@<GIT_COMMIT>@${GIT_COMMIT}@g"     ${versionfile}
    sed -i "s@<GIT_BRANCH>@${GIT_BRANCH}@g"     ${versionfile}
    sed -i "s@<GIT_URL>@${GIT_URL}@g"           ${versionfile}
    sed -i "s@<VERSION_UTILITIES>@${version}@g" ${versionfile}
done

mvn versions:set -DnewVersion=${version}
mvn versions:use-releases
mvn versions:use-latest-releases
